---获取到当前所有要刷新的视图

SELECT DISTINCT  
        'EXEC sp_refreshview ''' + name + ''''  
FROM    sys.objects AS so  
        INNER JOIN sys.sql_expression_dependencies AS sed ON so.object_id = sed.referencing_id  
WHERE   so.type = 'V'  

EXEC sp_refreshview 'geren_liushui2013'
EXEC sp_refreshview 'geren_yue'
EXEC sp_refreshview 'qiye_all_duizhang_bank_new'
EXEC sp_refreshview 'v_caiwu_zhanghu_djf_buchongyiliao'
EXEC sp_refreshview 'v_caiwu_zhanghu_djf_cundangyewu'
EXEC sp_refreshview 'v_caiwu_zhanghu_djf_cunjitihuyewu'
EXEC sp_refreshview 'v_caiwu_zhanghu_djf_daifagongziyewu'
EXEC sp_refreshview 'v_caiwu_zhanghu_djf_daishoucanbaojin'
EXEC sp_refreshview 'v_caiwu_zhanghu_djf_geren_geshuiyewu'
EXEC sp_refreshview 'v_caiwu_zhanghu_djf_geshuiyewu'
EXEC sp_refreshview 'v_caiwu_zhanghu_djf_gongjijinbujiaoyewu'
EXEC sp_refreshview 'v_caiwu_zhanghu_djf_gongjijintiquyewu'
EXEC sp_refreshview 'v_caiwu_zhanghu_djf_gongjijinyewu'
EXEC sp_refreshview 'v_caiwu_zhanghu_djf_gongzuojuzhuzhengyewu'
EXEC sp_refreshview 'v_caiwu_zhanghu_djf_kehu'
EXEC sp_refreshview 'v_caiwu_zhanghu_djf_kuanianbujiaoyewu'
EXEC sp_refreshview 'v_caiwu_zhanghu_djf_qichu_yue'
EXEC sp_refreshview 'v_caiwu_zhanghu_djf_qitayewu'
EXEC sp_refreshview 'v_caiwu_zhanghu_djf_qiye_geshuiyewu'
EXEC sp_refreshview 'v_caiwu_zhanghu_djf_shebaobujiaoyewu'
EXEC sp_refreshview 'v_caiwu_zhanghu_djf_shebaoyewu'
EXEC sp_refreshview 'v_caiwu_zhanghu_djf_waidigongjijinbujiaoyewu'
EXEC sp_refreshview 'v_caiwu_zhanghu_djf_waidigongjijinyewu'
EXEC sp_refreshview 'v_caiwu_zhanghu_djf_waidishebaobujiaoyewu'
EXEC sp_refreshview 'v_caiwu_zhanghu_djf_waidishebaoyewu'
EXEC sp_refreshview 'v_caiwu_zhanghu_djf_waidiyewu'
EXEC sp_refreshview 'v_caiwu_zhanghu_djf_yinanyewu'
EXEC sp_refreshview 'v_caiwu_zhanghu_djf_zhouzhuanzijin'
EXEC sp_refreshview 'v_caiwu_zhanghu_fwf_lirunzhanghu'
EXEC sp_refreshview 'V_Customer_geren_gerenExtended_GerenProduct_Curr'
EXEC sp_refreshview 'V_Customer_geren_gerenExtended_GerenProduct_Curr_gerenfwfjixiao'
EXEC sp_refreshview 'V_Customer_qiyeVSyuangong'
EXEC sp_refreshview 'V_Customer_QiyeYuangongProduct'
EXEC sp_refreshview 'v_geren_hebingkehu_new'
EXEC sp_refreshview 'v_lc_qiyeWork'
EXEC sp_refreshview 'V_Money_qiye'
EXEC sp_refreshview 'V_Money_YuanGongProduct'
EXEC sp_refreshview 'V_Money_YuanGongProduct_curr'
EXEC sp_refreshview 'V_qiye_gongzi_curr'
EXEC sp_refreshview 'v_qiye_hebingkehu_new'
EXEC sp_refreshview 'V_qiye_liushui2013'
EXEC sp_refreshview 'V_Report_geren_DangAn'
EXEC sp_refreshview 'V_Report_geren_geshui'
EXEC sp_refreshview 'V_Report_geren_gongjijin'
EXEC sp_refreshview 'V_Report_geren_gongzi'
EXEC sp_refreshview 'V_Report_geren_shebao'
EXEC sp_refreshview 'V_Report_qiye_DangAn'
EXEC sp_refreshview 'V_Report_qiye_geshui'
EXEC sp_refreshview 'V_Report_qiye_gongjijin'
EXEC sp_refreshview 'V_Report_qiye_gongjijin_waidi'
EXEC sp_refreshview 'V_Report_qiye_shebao'
EXEC sp_refreshview 'V_Report_qiye_shebao_waidi'
EXEC sp_refreshview 'V_Report_qiye_shebaogongjijin'
EXEC sp_refreshview 'V_Report_qiye_ZaizhiYuanGong'
EXEC sp_refreshview 'v_sys_Down_Data_gjj'
EXEC sp_refreshview 'v_sys_Down_Data_gjj_rz'
EXEC sp_refreshview 'v_sys_Down_Data_sb'
EXEC sp_refreshview 'v_sys_Down_Data_sb_allperson'
EXEC sp_refreshview 'v_sys_Down_ruihua_Data_gjj'
EXEC sp_refreshview 'v_sys_Down_ruihua_Data_gjj_rz'
EXEC sp_refreshview 'v_sys_Down_ruihua_Data_sb'
EXEC sp_refreshview 'v_sys_Down_ruihua_Data_sb_allperson'
EXEC sp_refreshview 'V_T_Money_gerenProduct'
EXEC sp_refreshview 'V_T_Money_YuanGongProduct'
EXEC sp_refreshview 'V_Work_Notice'
EXEC sp_refreshview 'v_zijin_mingxi_shitu'